apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tim-sample-app
  name: tim-sample-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tim-sample-app
  strategy:
  template:
    metadata:
      labels:
        app: tim-sample-app
    spec:
      containers:
      - name: tim-sample-app
        image: barrywilliams/tim-sample-app
        imagePullPolicy: Always
        env:
        - name: HTML_BG_COLOR
          value: LightGreen
        - name: CONSUMED_CPU_MODE
          value: random
        resources: 
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 200Mi
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /alive
            port: 4567
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 4567
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 4567
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tim-sample-app
  name: tim-sample-app
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 4567
  selector:
    app: tim-sample-app
  type: ClusterIP